<template>
  <div class="user-avatar d-flex align-center">
    <div class="avatar-wrapper" :style="{ width: size + 'px', height: size + 'px' }">
      <img :src="user.avatar || `/api/users/${user.id}/avatar`" :alt="user.display_name" class="avatar-img" />
    </div>
    <div v-if="showUsername" class="user-info">
      <div class="user-name" :class="nameSizeClass">{{ user.display_name || user.username }}</div>
      <div class="titles-row">
        <template v-for="title in displayTitles" :key="title.id || 'default'">
          <span
            class="title-chip"
            :style="{ backgroundColor: adjustColorOpacity(title.color, 0.12), color: title.color, border: `1px solid ${adjustColorOpacity(title.color, 0.25)}` }"
          >
            <i v-if="title.icon" :class="getIconClass(title.icon)" class="chip-icon"></i>
            {{ title.name }}
          </span>
        </template>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  user: {
    type: Object,
    required: true
  },
  size: {
    type: Number,
    default: 40
  },
  showUsername: {
    type: Boolean,
    default: true
  },
  maxVisibleTitles: {
    type: Number,
    default: 2
  }
})

const mdiToFa = {
  'mdi-account': 'fa-solid fa-user',
  'mdi-star': 'fa-solid fa-star',
  'mdi-trophy': 'fa-solid fa-trophy',
  'mdi-crown': 'fa-solid fa-crown',
  'mdi-medal': 'fa-solid fa-medal',
  'mdi-award': 'fa-solid fa-award',
  'mdi-badge': 'fa-solid fa-award',
  'mdi-circle': 'fa-solid fa-circle',
  'mdi-heart': 'fa-solid fa-heart',
  'mdi-heart-outline': 'fa-regular fa-heart',
  'mdi-lightbulb': 'fa-solid fa-lightbulb',
  'mdi-code': 'fa-solid fa-code',
  'mdi-book': 'fa-solid fa-book',
  'mdi-book-open': 'fa-solid fa-book-open',
  'mdi-pencil': 'fa-solid fa-pencil',
  'mdi-pen': 'fa-solid fa-pen-to-square',
  'mdi-message': 'fa-solid fa-message',
  'mdi-comment': 'fa-solid fa-comment',
  'mdi-eye': 'fa-solid fa-eye',
  'mdi-globe': 'fa-solid fa-globe',
  'mdi-flag': 'fa-solid fa-flag',
  'mdi-rocket': 'fa-solid fa-rocket',
  'mdi-flame': 'fa-solid fa-flame',
  'mdi-leaf': 'fa-solid fa-leaf',
  'mdi-tree': 'fa-solid fa-tree',
  'mdi-cloud': 'fa-solid fa-cloud',
  'mdi-sun': 'fa-solid fa-sun',
  'mdi-moon': 'fa-solid fa-moon',
  'mdi-star-outline': 'fa-regular fa-star',
  'mdi-star-half': 'fa-solid fa-star-half-stroke',
  'mdi-thumbs-up': 'fa-solid fa-thumbs-up',
  'mdi-thumbs-down': 'fa-solid fa-thumbs-down',
  'mdi-share': 'fa-solid fa-share-nodes',
  'mdi-link': 'fa-solid fa-link',
  'mdi-external-link': 'fa-solid fa-external-link',
  'mdi-home': 'fa-solid fa-house',
  'mdi-settings': 'fa-solid fa-gear',
  'mdi-cog': 'fa-solid fa-gear',
  'mdi-lock': 'fa-solid fa-lock',
  'mdi-unlock': 'fa-solid fa-unlock',
  'mdi-bell': 'fa-solid fa-bell',
  'mdi-bell-ring': 'fa-solid fa-bell',
  'mdi-calendar': 'fa-solid fa-calendar',
  'mdi-clock': 'fa-solid fa-clock',
  'mdi-image': 'fa-solid fa-image',
  'mdi-video': 'fa-solid fa-video',
  'mdi-file': 'fa-solid fa-file',
  'mdi-file-text': 'fa-solid fa-file-lines',
  'mdi-folder': 'fa-solid fa-folder',
  'mdi-tag': 'fa-solid fa-tag',
  'mdi-users': 'fa-solid fa-users',
  'mdi-user': 'fa-solid fa-user',
  'mdi-user-circle': 'fa-solid fa-user-circle',
  'mdi-account': 'fa-solid fa-user',
  'mdi-account-circle': 'fa-solid fa-user-circle',
  'mdi-account-group': 'fa-solid fa-users',
  'mdi-group': 'fa-solid fa-users',
  'mdi-upload': 'fa-solid fa-upload',
  'mdi-download': 'fa-solid fa-download',
  'mdi-save': 'fa-solid fa-floppy-disk',
  'mdi-delete': 'fa-solid fa-trash',
  'mdi-edit': 'fa-solid fa-pencil',
  'mdi-plus': 'fa-solid fa-plus',
  'mdi-minus': 'fa-solid fa-minus',
  'mdi-check': 'fa-solid fa-check',
  'mdi-close': 'fa-solid fa-xmark',
  'mdi-x': 'fa-solid fa-xmark',
  'mdi-alert': 'fa-solid fa-circle-exclamation',
  'mdi-alert-circle': 'fa-solid fa-circle-exclamation',
  'mdi-info': 'fa-solid fa-circle-info',
  'mdi-help': 'fa-solid fa-circle-question',
  'mdi-help-circle': 'fa-solid fa-circle-question',
  'mdi-search': 'fa-solid fa-search',
  'mdi-magnify': 'fa-solid fa-magnifying-glass',
  'mdi-filter': 'fa-solid fa-filter',
  'mdi-sort': 'fa-solid fa-arrow-down-wide-short',
  'mdi-refresh': 'fa-solid fa-rotate-right',
  'mdi-reload': 'fa-solid fa-rotate-right',
  'mdi-play': 'fa-solid fa-play',
  'mdi-pause': 'fa-solid fa-pause',
  'mdi-volume-high': 'fa-solid fa-volume-high',
  'mdi-volume-mute': 'fa-solid fa-volume-xmark',
  'mdi-fullscreen': 'fa-solid fa-expand',
  'mdi-list': 'fa-solid fa-list',
  'mdi-grid': 'fa-solid fa-grid-3x3',
  'mdi-chart-bar': 'fa-solid fa-chart-bar',
  'mdi-chart-line': 'fa-solid fa-chart-line',
  'mdi-chart-pie': 'fa-solid fa-chart-pie',
  'mdi-wallet': 'fa-solid fa-wallet',
  'mdi-coins': 'fa-solid fa-coins',
  'mdi-gift': 'fa-solid fa-gift',
  'mdi-shield': 'fa-solid fa-shield',
  'mdi-shield-check': 'fa-solid fa-shield-check',
  'mdi-key': 'fa-solid fa-key',
  'mdi-message-circle': 'fa-solid fa-comment-circle',
  'mdi-bookmark': 'fa-solid fa-bookmark',
  'mdi-bookmark-outline': 'fa-regular fa-bookmark',
  'mdi-rss': 'fa-solid fa-rss',
  'mdi-lightbulb-outline': 'fa-regular fa-lightbulb',
  'mdi-smile': 'fa-solid fa-face-smile',
  'mdi-frown': 'fa-solid fa-face-frown',
  'mdi-meh': 'fa-solid fa-face-meh',
  'mdi-hand': 'fa-solid fa-hand',
  'mdi-hand-heart': 'fa-solid fa-heart-handshake',
  'mdi-handshake': 'fa-solid fa-handshake',
  'mdi-thumbs-up-down': 'fa-solid fa-thumbs-up-down',
  'mdi-brain': 'fa-solid fa-brain',
  'mdi-cpu': 'fa-solid fa-cpu',
  'mdi-database': 'fa-solid fa-database',
  'mdi-server': 'fa-solid fa-server',
  'mdi-network': 'fa-solid fa-network-wired',
  'mdi-wifi': 'fa-solid fa-wifi',
  'mdi-bluetooth': 'fa-brands fa-bluetooth',
  'mdi-usb': 'fa-solid fa-usb',
  'mdi-printer': 'fa-solid fa-printer',
  'mdi-scanner': 'fa-solid fa-scanner',
  'mdi-monitor': 'fa-solid fa-monitor',
  'mdi-laptop': 'fa-solid fa-laptop',
  'mdi-tablet': 'fa-solid fa-tablet-screen-button',
  'mdi-smartphone': 'fa-solid fa-mobile-screen-button',
  'mdi-gamepad': 'fa-solid fa-gamepad',
  'mdi-controller': 'fa-solid fa-gamepad',
  'mdi-joystick': 'fa-solid fa-gamepad-2',
  'mdi-music': 'fa-solid fa-music',
  'mdi-headphones': 'fa-solid fa-headphones',
  'mdi-microphone': 'fa-solid fa-microphone',
  'mdi-speaker': 'fa-solid fa-volume-high',
  'mdi-camera': 'fa-solid fa-camera',
  'mdi-video-camera': 'fa-solid fa-video',
  'mdi-picture': 'fa-solid fa-image',
  'mdi-image-plus': 'fa-solid fa-image-plus',
  'mdi-video-plus': 'fa-solid fa-video-plus',
  'mdi-film': 'fa-solid fa-film',
  'mdi-clapperboard': 'fa-solid fa-clapperboard',
  'mdi-photo': 'fa-solid fa-image',
  'mdi-photo-camera': 'fa-solid fa-camera',
  'mdi-palette': 'fa-solid fa-palette',
  'mdi-brush': 'fa-solid fa-brush',
  'mdi-paint': 'fa-solid fa-paintbrush',
  'mdi-pencil-ruler': 'fa-solid fa-ruler-combined',
  'mdi-ruler': 'fa-solid fa-ruler',
  'mdi-compass': 'fa-solid fa-compass',
  'mdi-map': 'fa-solid fa-map',
  'mdi-map-marker': 'fa-solid fa-map-pin',
  'mdi-navigation': 'fa-solid fa-compass',
  'mdi-location': 'fa-solid fa-map-pin',
  'mdi-globe-2': 'fa-solid fa-globe',
  'mdi-earth': 'fa-solid fa-globe',
  'mdi-mountain': 'fa-solid fa-mountain',
  'mdi-tent': 'fa-solid fa-tent',
  'mdi-tree-pine': 'fa-solid fa-tree',
  'mdi-tree-deciduous': 'fa-solid fa-tree',
  'mdi-flower': 'fa-solid fa-flower-2',
  'mdi-leaf-flower': 'fa-solid fa-leaf',
  'mdi-water': 'fa-solid fa-droplet',
  'mdi-fire': 'fa-solid fa-flame',
  'mdi-snowflake': 'fa-solid fa-snowflake',
  'mdi-cloud-sun': 'fa-solid fa-cloud-sun',
  'mdi-cloud-rain': 'fa-solid fa-cloud-rain',
  'mdi-cloud-lightning': 'fa-solid fa-cloud-bolt',
  'mdi-weather-sunny': 'fa-solid fa-sun',
  'mdi-weather-night': 'fa-solid fa-moon',
  'mdi-weather-cloudy': 'fa-solid fa-cloud',
  'mdi-weather-rainy': 'fa-solid fa-cloud-rain',
  'mdi-weather-snowy': 'fa-solid fa-snowflake',
  'mdi-weather-windy': 'fa-solid fa-wind',
  'mdi-clock-alert': 'fa-solid fa-clock-exclamation',
  'mdi-calendar-check': 'fa-solid fa-calendar-check',
  'mdi-calendar-clock': 'fa-solid fa-calendar-clock',
  'mdi-calendar-plus': 'fa-solid fa-calendar-plus',
  'mdi-calendar-minus': 'fa-solid fa-calendar-minus',
  'mdi-calendar-edit': 'fa-solid fa-calendar-pen',
  'mdi-bell-plus': 'fa-solid fa-bell-plus',
  'mdi-bell-minus': 'fa-solid fa-bell-minus',
  'mdi-bell-off': 'fa-solid fa-bell-slash',
  'mdi-bell-ring': 'fa-solid fa-bell',
  'mdi-notification': 'fa-solid fa-bell',
  'mdi-notification-clear-all': 'fa-solid fa-bell',
  'mdi-email': 'fa-solid fa-envelope',
  'mdi-email-open': 'fa-solid fa-envelope-open',
  'mdi-email-check': 'fa-solid fa-envelope-check',
  'mdi-email-alert': 'fa-solid fa-envelope-circle-check',
  'mdi-email-off': 'fa-solid fa-envelope-xmark',
  'mdi-send': 'fa-solid fa-paper-plane',
  'mdi-send-outline': 'fa-solid fa-paper-plane',
  'mdi-reply': 'fa-solid fa-reply',
  'mdi-reply-all': 'fa-solid fa-reply-all',
  'mdi-forward': 'fa-solid fa-forward',
  'mdi-message-square': 'fa-solid fa-message',
  'mdi-message-square-outline': 'fa-regular fa-message',
  'mdi-chat': 'fa-solid fa-comments',
  'mdi-chat-outline': 'fa-solid fa-comments',
  'mdi-forum': 'fa-solid fa-comments',
  'mdi-user-plus': 'fa-solid fa-user-plus',
  'mdi-user-minus': 'fa-solid fa-user-minus',
  'mdi-user-check': 'fa-solid fa-user-check',
  'mdi-user-edit': 'fa-solid fa-user-pen',
  'mdi-user-alert': 'fa-solid fa-user-exclamation',
  'mdi-user-off': 'fa-solid fa-user-xmark',
  'mdi-user-search': 'fa-solid fa-user-search',
  'mdi-user-gear': 'fa-solid fa-user-gear',
  'mdi-users-plus': 'fa-solid fa-users',
  'mdi-users-minus': 'fa-solid fa-users',
  'mdi-log-in': 'fa-solid fa-right-to-bracket',
  'mdi-log-out': 'fa-solid fa-right-from-bracket',
  'mdi-login': 'fa-solid fa-right-to-bracket',
  'mdi-logout': 'fa-solid fa-right-from-bracket',
  'mdi-sign-in': 'fa-solid fa-right-to-bracket',
  'mdi-sign-out': 'fa-solid fa-right-from-bracket',
  'mdi-apps': 'fa-solid fa-grid-3x3',
  'mdi-view-dashboard': 'fa-solid fa-gauge',
  'mdi-view-list': 'fa-solid fa-list',
  'mdi-view-grid': 'fa-solid fa-grid-3x3',
  'mdi-view-agenda': 'fa-solid fa-calendar-days',
  'mdi-layout-grid': 'fa-solid fa-grid-3x3',
  'mdi-layout-list': 'fa-solid fa-list',
  'mdi-layout-sidebar': 'fa-solid fa-columns',
  'mdi-layout-bottom-panel': 'fa-solid fa-window-maximize',
  'mdi-layout-top-panel': 'fa-solid fa-window-minimize',
  'mdi-fullscreen': 'fa-solid fa-expand',
  'mdi-fullscreen-exit': 'fa-solid fa-compress',
  'mdi-maximize': 'fa-solid fa-maximize',
  'mdi-minimize': 'fa-solid fa-minimize',
  'mdi-window': 'fa-solid fa-window-maximize',
  'mdi-window-maximize': 'fa-solid fa-square-maximize',
  'mdi-window-minimize': 'fa-solid fa-square-minimize',
  'mdi-window-restore': 'fa-solid fa-square',
  'mdi-close-box': 'fa-solid fa-square-xmark',
  'mdi-minus-box': 'fa-solid fa-square-minus',
  'mdi-plus-box': 'fa-solid fa-square-plus',
  'mdi-open-in-new': 'fa-solid fa-external-link',
  'mdi-open-in-app': 'fa-solid fa-external-link',
  'mdi-duplicate': 'fa-solid fa-copy',
  'mdi-copy': 'fa-solid fa-copy',
  'mdi-cut': 'fa-solid fa-cut',
  'mdi-paste': 'fa-solid fa-paste',
  'mdi-clipboard': 'fa-solid fa-clipboard',
  'mdi-clipboard-list': 'fa-solid fa-clipboard-list',
  'mdi-clipboard-check': 'fa-solid fa-clipboard-check',
  'mdi-clipboard-edit': 'fa-solid fa-clipboard-pen',
  'mdi-clipboard-arrow-down': 'fa-solid fa-clipboard-download',
  'mdi-clipboard-arrow-up': 'fa-solid fa-clipboard-upload',
  'mdi-todo': 'fa-solid fa-list-checks',
  'mdi-list-checks': 'fa-solid fa-list-checks',
  'mdi-checkbox-marked': 'fa-solid fa-check-square',
  'mdi-checkbox-blank': 'fa-solid fa-square',
  'mdi-check-all': 'fa-solid fa-square-check',
  'mdi-check-square': 'fa-solid fa-check-square',
  'mdi-check-square-outline': 'fa-regular fa-check-square',
  'mdi-check-circle': 'fa-solid fa-circle-check',
  'mdi-check-circle-outline': 'fa-regular fa-circle-check',
  'mdi-close-circle': 'fa-solid fa-circle-xmark',
  'mdi-close-circle-outline': 'fa-regular fa-circle-xmark',
  'mdi-alert-circle-outline': 'fa-regular fa-circle-exclamation',
  'mdi-info-circle': 'fa-solid fa-circle-info',
  'mdi-help-circle-outline': 'fa-regular fa-circle-question',
  'mdi-minus-circle': 'fa-solid fa-circle-minus',
  'mdi-minus-circle-outline': 'fa-solid fa-circle-minus',
  'mdi-plus-circle': 'fa-solid fa-circle-plus',
  'mdi-plus-circle-outline': 'fa-solid fa-circle-plus',
  'mdi-lock-circle': 'fa-solid fa-lock',
  'mdi-lock-circle-outline': 'fa-solid fa-lock',
  'mdi-lock-open-circle': 'fa-solid fa-lock-open',
  'mdi-lock-open-circle-outline': 'fa-solid fa-lock-open',
  'mdi-pencil-circle': 'fa-solid fa-pen-to-square',
  'mdi-pencil-circle-outline': 'fa-solid fa-pen-to-square',
  'mdi-delete-circle': 'fa-solid fa-trash',
  'mdi-delete-circle-outline': 'fa-solid fa-trash',
  'mdi-download-circle': 'fa-solid fa-download',
  'mdi-download-circle-outline': 'fa-solid fa-download',
  'mdi-upload-circle': 'fa-solid fa-upload',
  'mdi-upload-circle-outline': 'fa-solid fa-upload',
  'mdi-share-circle': 'fa-solid fa-share-nodes',
  'mdi-share-circle-outline': 'fa-solid fa-share-nodes',
  'mdi-star-circle': 'fa-solid fa-star',
  'mdi-star-circle-outline': 'fa-regular fa-star',
  'mdi-heart-circle': 'fa-solid fa-heart',
  'mdi-heart-circle-outline': 'fa-regular fa-heart',
  'mdi-bookmark-circle': 'fa-solid fa-bookmark',
  'mdi-bookmark-circle-outline': 'fa-regular fa-bookmark',
  'mdi-calendar-circle': 'fa-solid fa-calendar',
  'mdi-calendar-circle-outline': 'fa-solid fa-calendar',
  'mdi-clock-circle': 'fa-solid fa-clock',
  'mdi-clock-circle-outline': 'fa-solid fa-clock',
  'mdi-bell-circle': 'fa-solid fa-bell',
  'mdi-bell-circle-outline': 'fa-regular fa-bell',
  'mdi-mail-circle': 'fa-solid fa-envelope',
  'mdi-mail-circle-outline': 'fa-solid fa-envelope',
  'mdi-phone-circle': 'fa-solid fa-phone',
  'mdi-phone-circle-outline': 'fa-solid fa-phone',
  'mdi-map-marker-circle': 'fa-solid fa-map-pin',
  'mdi-map-marker-circle-outline': 'fa-solid fa-map-pin',
  'mdi-globe-circle': 'fa-solid fa-globe',
  'mdi-globe-circle-outline': 'fa-solid fa-globe',
  'mdi-camera-circle': 'fa-solid fa-camera',
  'mdi-camera-circle-outline': 'fa-solid fa-camera',
  'mdi-image-circle': 'fa-solid fa-image',
  'mdi-image-circle-outline': 'fa-solid fa-image',
  'mdi-video-circle': 'fa-solid fa-video',
  'mdi-video-circle-outline': 'fa-solid fa-video',
  'mdi-file-circle': 'fa-solid fa-file',
  'mdi-file-circle-outline': 'fa-solid fa-file',
  'mdi-folder-circle': 'fa-solid fa-folder',
  'mdi-folder-circle-outline': 'fa-solid fa-folder',
  'mdi-link-circle': 'fa-solid fa-link',
  'mdi-link-circle-outline': 'fa-solid fa-link',
  'mdi-tag-circle': 'fa-solid fa-tag',
  'mdi-tag-circle-outline': 'fa-solid fa-tag',
  'mdi-chart-circle': 'fa-solid fa-chart-pie',
  'mdi-chart-circle-outline': 'fa-solid fa-chart-pie',
  'mdi-trending-circle': 'fa-solid fa-trending-up',
  'mdi-trending-circle-outline': 'fa-solid fa-trending-up',
  'mdi-wallet-circle': 'fa-solid fa-wallet',
  'mdi-wallet-circle-outline': 'fa-solid fa-wallet',
  'mdi-coins-circle': 'fa-solid fa-coins',
  'mdi-coins-circle-outline': 'fa-solid fa-coins',
  'mdi-gift-circle': 'fa-solid fa-gift',
  'mdi-gift-circle-outline': 'fa-solid fa-gift',
  'mdi-trophy-circle': 'fa-solid fa-trophy',
  'mdi-trophy-circle-outline': 'fa-solid fa-trophy',
  'mdi-award-circle': 'fa-solid fa-award',
  'mdi-award-circle-outline': 'fa-solid fa-award',
  'mdi-medal-circle': 'fa-solid fa-medal',
  'mdi-medal-circle-outline': 'fa-solid fa-medal',
  'mdi-crown-circle': 'fa-solid fa-crown',
  'mdi-crown-circle-outline': 'fa-solid fa-crown',
  'mdi-shield-circle': 'fa-solid fa-shield',
  'mdi-shield-circle-outline': 'fa-solid fa-shield',
  'mdi-key-circle': 'fa-solid fa-key',
  'mdi-key-circle-outline': 'fa-solid fa-key',
  'mdi-eye-circle': 'fa-solid fa-eye',
  'mdi-eye-circle-outline': 'fa-solid fa-eye',
  'mdi-eye-off-circle': 'fa-solid fa-eye-slash',
  'mdi-eye-off-circle-outline': 'fa-solid fa-eye-slash',
  'mdi-eye-check-circle': 'fa-solid fa-eye-check',
  'mdi-eye-check-circle-outline': 'fa-solid fa-eye-check',
  'mdi-eye-alert-circle': 'fa-solid fa-eye-exclamation',
  'mdi-eye-alert-circle-outline': 'fa-solid fa-eye-exclamation',
  'mdi-face-circle': 'fa-solid fa-face-smile',
  'mdi-face-circle-outline': 'fa-solid fa-face-smile',
  'mdi-face-off-circle': 'fa-solid fa-face-frown',
  'mdi-face-off-circle-outline': 'fa-solid fa-face-frown',
  'mdi-account-circle-outline': 'fa-regular fa-user',
  'mdi-account-circle-off-outline': 'fa-solid fa-user-xmark',
  'mdi-account-check-circle-outline': 'fa-solid fa-user-check',
  'mdi-account-alert-circle-outline': 'fa-solid fa-user-exclamation',
  'mdi-account-edit-circle-outline': 'fa-solid fa-user-pen',
  'mdi-account-plus-circle-outline': 'fa-solid fa-user-plus',
  'mdi-account-minus-circle-outline': 'fa-solid fa-user-minus',
  'mdi-account-multiple-circle-outline': 'fa-solid fa-users',
  'mdi-account-group-circle-outline': 'fa-solid fa-users',
  'mdi-account-settings-circle-outline': 'fa-solid fa-user-gear',
  'mdi-account-search-circle-outline': 'fa-solid fa-user-search',
  'mdi-account-off-outline': 'fa-solid fa-user-xmark',
  'mdi-account-check-outline': 'fa-solid fa-user-check',
  'mdi-account-alert-outline': 'fa-solid fa-user-exclamation',
  'mdi-account-edit-outline': 'fa-solid fa-user-pen',
  'mdi-account-plus-outline': 'fa-solid fa-user-plus',
  'mdi-account-minus-outline': 'fa-solid fa-user-minus',
  'mdi-account-multiple-outline': 'fa-solid fa-users',
  'mdi-account-group-outline': 'fa-solid fa-users',
  'mdi-account-settings-outline': 'fa-solid fa-user-gear',
  'mdi-account-search-outline': 'fa-solid fa-user-search',
  'mdi-grid-3x3': 'fa-solid fa-grid-3x3',
  'mdi-grid-2x2': 'fa-solid fa-grid-2x2',
  'mdi-grid-large': 'fa-solid fa-grid-3x3',
  'mdi-grid-small': 'fa-solid fa-grid-2x2',
  'mdi-list-outline': 'fa-solid fa-list',
  'mdi-list-box': 'fa-solid fa-list-checks',
  'mdi-list-checks-outline': 'fa-solid fa-list-checks',
  'mdi-list-ordered': 'fa-solid fa-list-ol',
  'mdi-list-unordered': 'fa-solid fa-list',
  'mdi-tree': 'fa-solid fa-folder-tree',
  'mdi-tree-outline': 'fa-solid fa-folder-tree',
  'mdi-view-dashboard-outline': 'fa-solid fa-gauge',
  'mdi-view-dashboard-variant': 'fa-solid fa-gauge',
  'mdi-view-dashboard-variant-outline': 'fa-solid fa-gauge',
  'mdi-view-list-outline': 'fa-solid fa-list',
  'mdi-view-grid-outline': 'fa-solid fa-grid-3x3',
  'mdi-view-agenda-outline': 'fa-solid fa-calendar-days',
  'mdi-view-headline': 'fa-solid fa-list',
  'mdi-view-headline-outline': 'fa-solid fa-list',
  'mdi-view-subtitles': 'fa-solid fa-closed-captioning',
  'mdi-view-subtitles-outline': 'fa-solid fa-closed-captioning',
  'mdi-view-text': 'fa-solid fa-file-lines',
  'mdi-view-text-outline': 'fa-solid fa-file-lines',
  'mdi-view-column': 'fa-solid fa-columns',
  'mdi-view-column-outline': 'fa-solid fa-columns',
  'mdi-view-carousel': 'fa-solid fa-images',
  'mdi-view-carousel-outline': 'fa-solid fa-images',
  'mdi-view-array': 'fa-solid fa-grid-3x3',
  'mdi-view-array-outline': 'fa-solid fa-grid-3x3',
  'mdi-view-compact': 'fa-solid fa-grid-2x2',
  'mdi-view-compact-outline': 'fa-solid fa-grid-2x2',
  'mdi-view-fullscreen-outline': 'fa-solid fa-expand',
  'mdi-view-split-vertical': 'fa-solid fa-grip-vertical',
  'mdi-view-split-vertical-outline': 'fa-solid fa-grip-vertical',
  'mdi-view-split-horizontal': 'fa-solid fa-grip-horizontal',
  'mdi-view-split-horizontal-outline': 'fa-solid fa-grip-horizontal',
  'mdi-view-split': 'fa-solid fa-grip-horizontal',
  'mdi-view-split-outline': 'fa-solid fa-grip-horizontal',
  'mdi-gesture': 'fa-solid fa-hand',
  'mdi-gesture-tap': 'fa-solid fa-hand-pointer',
  'mdi-gesture-double-tap': 'fa-solid fa-hand-pointer',
  'mdi-gesture-swipe': 'fa-solid fa-hand',
  'mdi-gesture-swipe-left': 'fa-solid fa-hand',
  'mdi-gesture-swipe-right': 'fa-solid fa-hand',
  'mdi-gesture-swipe-up': 'fa-solid fa-hand',
  'mdi-gesture-swipe-down': 'fa-solid fa-hand',
  'mdi-gesture-zoom-in': 'fa-solid fa-magnifying-glass-plus',
  'mdi-gesture-zoom-out': 'fa-solid fa-magnifying-glass-minus',
  'mdi-gesture-rotate': 'fa-solid fa-rotate',
  'mdi-gesture-drag-horizontal': 'fa-solid fa-grip-horizontal',
  'mdi-gesture-drag-vertical': 'fa-solid fa-grip-vertical',
  'mdi-gesture-pinch': 'fa-solid fa-hand',
  'mdi-touchpad': 'fa-solid fa-square',
  'mdi-touchpad-off': 'fa-solid fa-square-xmark',
  'mdi-mouse-variant': 'fa-solid fa-computer-mouse',
  'mdi-mouse-variant-off': 'fa-solid fa-computer-mouse',
  'mdi-pointer': 'fa-solid fa-hand-pointer',
  'mdi-pointer-off': 'fa-solid fa-hand-pointer',
  'mdi-move': 'fa-solid fa-arrows-up-down-left-right',
  'mdi-move-horizontal': 'fa-solid fa-arrows-left-right',
  'mdi-move-vertical': 'fa-solid fa-arrows-up-down',
  'mdi-move-diagonal': 'fa-solid fa-arrows-up-down-left-right',
  'mdi-resize': 'fa-solid fa-maximize',
  'mdi-resize-horizontal': 'fa-solid fa-arrows-left-right',
  'mdi-resize-vertical': 'fa-solid fa-arrows-up-down',
  'mdi-resize-diagonal': 'fa-solid fa-maximize',
  'mdi-resize-diagonal-top': 'fa-solid fa-maximize',
  'mdi-resize-diagonal-bottom': 'fa-solid fa-maximize',
  'mdi-grip': 'fa-solid fa-grip-horizontal',
  'mdi-grip-horizontal': 'fa-solid fa-grip-horizontal',
  'mdi-grip-vertical': 'fa-solid fa-grip-vertical',
  'mdi-grip-lines': 'fa-solid fa-grip-horizontal',
  'mdi-grip-lines-horizontal': 'fa-solid fa-grip-horizontal',
  'mdi-grip-lines-vertical': 'fa-solid fa-grip-vertical',
  'mdi-grab': 'fa-solid fa-hand',
  'mdi-grab-horizontal': 'fa-solid fa-hand',
  'mdi-grab-vertical': 'fa-solid fa-hand',
  'mdi-grabbing': 'fa-solid fa-hand',
  'mdi-grabbing-horizontal': 'fa-solid fa-hand',
  'mdi-grabbing-vertical': 'fa-solid fa-hand',
  'mdi-arrow-left': 'fa-solid fa-arrow-left',
  'mdi-arrow-right': 'fa-solid fa-arrow-right',
  'mdi-arrow-up': 'fa-solid fa-arrow-up',
  'mdi-arrow-down': 'fa-solid fa-arrow-down',
  'mdi-arrow-left-bold': 'fa-solid fa-arrow-left',
  'mdi-arrow-right-bold': 'fa-solid fa-arrow-right',
  'mdi-arrow-up-bold': 'fa-solid fa-arrow-up',
  'mdi-arrow-down-bold': 'fa-solid fa-arrow-down',
  'mdi-arrow-left-bold-outline': 'fa-solid fa-arrow-left',
  'mdi-arrow-right-bold-outline': 'fa-solid fa-arrow-right',
  'mdi-arrow-up-bold-outline': 'fa-solid fa-arrow-up',
  'mdi-arrow-down-bold-outline': 'fa-solid fa-arrow-down',
  'mdi-chevron-left': 'fa-solid fa-chevron-left',
  'mdi-chevron-right': 'fa-solid fa-chevron-right',
  'mdi-chevron-up': 'fa-solid fa-chevron-up',
  'mdi-chevron-down': 'fa-solid fa-chevron-down',
  'mdi-chevron-left-circle': 'fa-solid fa-circle-chevron-left',
  'mdi-chevron-right-circle': 'fa-solid fa-circle-chevron-right',
  'mdi-chevron-up-circle': 'fa-solid fa-circle-chevron-up',
  'mdi-chevron-down-circle': 'fa-solid fa-circle-chevron-down',
  'mdi-chevron-left-bold': 'fa-solid fa-chevron-left',
  'mdi-chevron-right-bold': 'fa-solid fa-chevron-right',
  'mdi-chevron-up-bold': 'fa-solid fa-chevron-up',
  'mdi-chevron-down-bold': 'fa-solid fa-chevron-down',
  'mdi-menu': 'fa-solid fa-bars',
  'mdi-menu-down': 'fa-solid fa-chevron-down',
  'mdi-menu-up': 'fa-solid fa-chevron-up',
  'mdi-menu-left': 'fa-solid fa-chevron-left',
  'mdi-menu-right': 'fa-solid fa-chevron-right',
  'mdi-dots-horizontal': 'fa-solid fa-ellipsis-horizontal',
  'mdi-dots-vertical': 'fa-solid fa-ellipsis-vertical',
  'mdi-dots-three-horizontal': 'fa-solid fa-ellipsis-horizontal',
  'mdi-dots-three-vertical': 'fa-solid fa-ellipsis-vertical',
  'mdi-dots-horizontal-circle': 'fa-solid fa-circle-ellipsis-horizontal',
  'mdi-dots-vertical-circle': 'fa-solid fa-circle-ellipsis-vertical',
  'mdi-more-horizontal': 'fa-solid fa-ellipsis-horizontal',
  'mdi-more-vertical': 'fa-solid fa-ellipsis-vertical',
  'mdi-more-circle': 'fa-solid fa-circle-ellipsis-horizontal',
  'mdi-expand': 'fa-solid fa-expand',
  'mdi-expand-horizontal': 'fa-solid fa-expand',
  'mdi-expand-vertical': 'fa-solid fa-expand',
  'mdi-collapse': 'fa-solid fa-compress',
  'mdi-collapse-horizontal': 'fa-solid fa-compress',
  'mdi-collapse-vertical': 'fa-solid fa-compress',
  'mdi-minus': 'fa-solid fa-minus',
  'mdi-minus-bold': 'fa-solid fa-minus',
  'mdi-minus-square': 'fa-solid fa-square-minus',
  'mdi-minus-square-outline': 'fa-regular fa-square-minus',
  'mdi-plus': 'fa-solid fa-plus',
  'mdi-plus-bold': 'fa-solid fa-plus',
  'mdi-plus-square': 'fa-solid fa-square-plus',
  'mdi-plus-square-outline': 'fa-regular fa-square-plus',
  'mdi-check': 'fa-solid fa-check',
  'mdi-check-bold': 'fa-solid fa-check',
  'mdi-close': 'fa-solid fa-xmark',
  'mdi-close-bold': 'fa-solid fa-xmark',
  'mdi-x': 'fa-solid fa-xmark',
  'mdi-x-bold': 'fa-solid fa-xmark',
  'mdi-alert': 'fa-solid fa-triangle-exclamation',
  'mdi-alert-triangle': 'fa-solid fa-triangle-exclamation',
  'mdi-alert-octagon': 'fa-solid fa-octagon-exclamation',
  'mdi-info': 'fa-solid fa-circle-info',
  'mdi-help': 'fa-solid fa-circle-question',
  'mdi-help-circle': 'fa-solid fa-circle-question',
  'mdi-lightbulb': 'fa-solid fa-lightbulb',
  'mdi-lightbulb-outline': 'fa-regular fa-lightbulb',
  'mdi-sun': 'fa-solid fa-sun',
  'mdi-sun-outline': 'fa-solid fa-sun',
  'mdi-moon': 'fa-solid fa-moon',
  'mdi-moon-outline': 'fa-regular fa-moon',
  'mdi-cloud': 'fa-solid fa-cloud',
  'mdi-cloud-outline': 'fa-solid fa-cloud',
  'mdi-cloud-off': 'fa-solid fa-cloud-xmark',
  'mdi-cloud-sun': 'fa-solid fa-cloud-sun',
  'mdi-cloud-moon': 'fa-solid fa-cloud-moon',
  'mdi-cloud-rain': 'fa-solid fa-cloud-rain',
  'mdi-cloud-lightning': 'fa-solid fa-cloud-bolt',
  'mdi-cloud-snow': 'fa-solid fa-cloud-snow',
  'mdi-wind': 'fa-solid fa-wind',
  'mdi-snowflake': 'fa-solid fa-snowflake',
  'mdi-droplet': 'fa-solid fa-droplet',
  'mdi-droplet-off': 'fa-solid fa-droplet-slash',
  'mdi-droplet-outline': 'fa-solid fa-droplet',
  'mdi-fire': 'fa-solid fa-flame',
  'mdi-fire-outline': 'fa-solid fa-flame',
  'mdi-fire-alert': 'fa-solid fa-flame',
  'mdi-flame': 'fa-solid fa-flame',
  'mdi-flame-outline': 'fa-solid fa-flame',
  'mdi-ice-cream': 'fa-solid fa-ice-cream',
  'mdi-tree': 'fa-solid fa-tree',
  'mdi-tree-deciduous': 'fa-solid fa-tree',
  'mdi-tree-pine': 'fa-solid fa-tree',
  'mdi-leaf': 'fa-solid fa-leaf',
  'mdi-leaf-off': 'fa-solid fa-leaf',
  'mdi-flower': 'fa-solid fa-flower-2',
  'mdi-flower-2': 'fa-solid fa-flower-2',
  'mdi-grass': 'fa-solid fa-tree-pine',
  'mdi-nature': 'fa-solid fa-leaf',
  'mdi-mountain': 'fa-solid fa-mountain',
  'mdi-mountain-snow': 'fa-solid fa-mountain-snow',
  'mdi-volcano': 'fa-solid fa-mountain',
  'mdi-earth': 'fa-solid fa-globe',
  'mdi-earth-africa': 'fa-solid fa-globe',
  'mdi-earth-americas': 'fa-solid fa-globe',
  'mdi-earth-asia': 'fa-solid fa-globe',
  'mdi-earth-europe': 'fa-solid fa-globe',
  'mdi-globe': 'fa-solid fa-globe',
  'mdi-globe-outline': 'fa-solid fa-globe',
  'mdi-map': 'fa-solid fa-map',
  'mdi-map-outline': 'fa-solid fa-map',
  'mdi-map-marker': 'fa-solid fa-map-pin',
  'mdi-map-marker-radius': 'fa-solid fa-map-pin',
  'mdi-map-marker-minus': 'fa-solid fa-map-pin',
  'mdi-map-marker-plus': 'fa-solid fa-map-pin',
  'mdi-map-marker-off': 'fa-solid fa-map-pin',
  'mdi-map-search': 'fa-solid fa-map-location-dot',
  'mdi-compass': 'fa-solid fa-compass',
  'mdi-flag': 'fa-solid fa-flag',
  'mdi-flag-checkered': 'fa-solid fa-flag',
  'mdi-flag-outline': 'fa-regular fa-flag',
  'mdi-flag-cancel': 'fa-solid fa-flag',
  'mdi-circle': 'fa-solid fa-circle',
  'mdi-circle-outline': 'fa-regular fa-circle',
  'mdi-circle-dot': 'fa-solid fa-circle-dot',
  'mdi-circle-half': 'fa-solid fa-circle-half-stroke',
  'mdi-circle-slice-8': 'fa-solid fa-circle-quarter',
  'mdi-circle-slice-4': 'fa-solid fa-circle-half-stroke',
  'mdi-circle-slice-2': 'fa-solid fa-circle',
  'mdi-circle-multiple': 'fa-solid fa-circle-nodes',
  'mdi-circle-double': 'fa-solid fa-circle-nodes',
  'mdi-ring': 'fa-solid fa-circle',
  'mdi-ring-outline': 'fa-regular fa-circle',
  'mdi-record': 'fa-solid fa-circle',
  'mdi-disc': 'fa-solid fa-circle',
  'mdi-cd': 'fa-solid fa-compact-disc',
  'mdi-square': 'fa-solid fa-square',
  'mdi-square-outline': 'fa-regular fa-square',
  'mdi-square-off-outline': 'fa-regular fa-square',
  'mdi-rectangle': 'fa-solid fa-rectangle-horizontal',
  'mdi-rectangle-outline': 'fa-solid fa-rectangle-horizontal',
  'mdi-rectangle-horizontal': 'fa-solid fa-rectangle-horizontal',
  'mdi-rectangle-vertical': 'fa-solid fa-rectangle-vertical',
  'mdi-triangle': 'fa-solid fa-triangle',
  'mdi-triangle-outline': 'fa-solid fa-triangle',
  'mdi-diamond': 'fa-solid fa-diamond',
  'mdi-diamond-outline': 'fa-solid fa-diamond',
  'mdi-octagon': 'fa-solid fa-octagon',
  'mdi-octagon-outline': 'fa-solid fa-octagon',
  'mdi-pentagon': 'fa-solid fa-pentagon',
  'mdi-pentagon-outline': 'fa-solid fa-pentagon',
  'mdi-hexagon': 'fa-solid fa-hexagon',
  'mdi-hexagon-outline': 'fa-regular fa-hexagon',
  'mdi-play-circle': 'fa-solid fa-circle-play',
  'mdi-play-circle-outline': 'fa-regular fa-circle-play',
  'mdi-pause-circle': 'fa-solid fa-circle-pause',
  'mdi-pause-circle-outline': 'fa-regular fa-circle-pause',
  'mdi-stop-circle': 'fa-solid fa-circle-stop',
  'mdi-stop-circle-outline': 'fa-regular fa-circle-stop',
  'mdi-skip-next': 'fa-solid fa-forward-step',
  'mdi-skip-previous': 'fa-solid fa-backward-step',
  'mdi-fast-forward': 'fa-solid fa-fast-forward',
  'mdi-fast-rewind': 'fa-solid fa-fast-backward',
  'mdi-shuffle': 'fa-solid fa-shuffle',
  'mdi-repeat': 'fa-solid fa-repeat',
  'mdi-repeat-once': 'fa-solid fa-repeat-1',
  'mdi-repeat-variant': 'fa-solid fa-repeat',
  'mdi-volume-1': 'fa-solid fa-volume-low',
  'mdi-volume-2': 'fa-solid fa-volume-high',
  'mdi-volume-medium': 'fa-solid fa-volume-medium',
  'mdi-volume-minus': 'fa-solid fa-volume-down',
  'mdi-volume-plus': 'fa-solid fa-volume-up',
  'mdi-volume-mute': 'fa-solid fa-volume-xmark',
  'mdi-subtitles': 'fa-solid fa-closed-captioning',
  'mdi-subtitles-outline': 'fa-solid fa-closed-captioning',
  'mdi-captions': 'fa-solid fa-closed-captioning',
  'mdi-captions-off': 'fa-solid fa-closed-captioning',
  'mdi-aspect-ratio': 'fa-solid fa-square',
  'mdi-aspect-ratio-box': 'fa-solid fa-square',
  'mdi-crop': 'fa-solid fa-crop',
  'mdi-crop-16-9': 'fa-solid fa-square',
  'mdi-crop-4-3': 'fa-solid fa-square',
  'mdi-crop-free': 'fa-solid fa-square',
  'mdi-rotate': 'fa-solid fa-rotate',
  'mdi-rotate-3d': 'fa-solid fa-rotate',
  'mdi-rotate-ccw': 'fa-solid fa-rotate-left',
  'mdi-rotate-cw': 'fa-solid fa-rotate-right',
  'mdi-flip': 'fa-solid fa-arrows-up-down-left-right',
  'mdi-flip-horizontal': 'fa-solid fa-rotate-horizontal',
  'mdi-flip-vertical': 'fa-solid fa-rotate-vertical',
  'mdi-mirror': 'fa-solid fa-rotate-horizontal',
  'mdi-step-forward': 'fa-solid fa-step-forward',
  'mdi-step-backward': 'fa-solid fa-step-backward',
  'mdi-eject': 'fa-solid fa-eject',
  'mdi-music': 'fa-solid fa-music',
  'mdi-music-box': 'fa-solid fa-music',
  'mdi-music-circle': 'fa-solid fa-music',
  'mdi-disc-4': 'fa-solid fa-disc',
  'mdi-disc-3': 'fa-solid fa-disc',
  'mdi-disc-2': 'fa-solid fa-disc',
  'mdi-disc-1': 'fa-solid fa-disc',
  'mdi-bluetooth': 'fa-brands fa-bluetooth',
  'mdi-bluetooth-audio': 'fa-brands fa-bluetooth-b',
  'mdi-headphones-bluetooth': 'fa-solid fa-headphones',
  'mdi-speaker-bluetooth': 'fa-solid fa-volume-high',
  'mdi-cpu': 'fa-solid fa-cpu',
  'mdi-harddrive': 'fa-solid fa-hard-drive',
  'mdi-memory': 'fa-solid fa-memory-stick',
  'mdi-network': 'fa-solid fa-network-wired',
  'mdi-bluetooth-off': 'fa-solid fa-bluetooth-b',
  'mdi-usb': 'fa-solid fa-usb',
  'mdi-printer': 'fa-solid fa-printer',
  'mdi-scanner': 'fa-solid fa-scanner',
  'mdi-monitor': 'fa-solid fa-monitor',
  'mdi-laptop': 'fa-solid fa-laptop',
  'mdi-tablet': 'fa-solid fa-tablet-screen-button',
  'mdi-smartphone': 'fa-solid fa-mobile-screen-button',
  'mdi-watch': 'fa-solid fa-watch',
  'mdi-calculator': 'fa-solid fa-calculator',
  'mdi-keyboard': 'fa-solid fa-keyboard',
  'mdi-gamepad': 'fa-solid fa-gamepad',
  'mdi-joystick': 'fa-solid fa-gamepad-2',
  'mdi-controller': 'fa-solid fa-gamepad',
  'mdi-beaker': 'fa-solid fa-flask-conical',
  'mdi-flask': 'fa-solid fa-flask-vial',
  'mdi-dna': 'fa-solid fa-dna',
  'mdi-molecule': 'fa-solid fa-atom',
  'mdi-atom': 'fa-solid fa-atom',
  'mdi-robot': 'fa-solid fa-robot',
  'mdi-cog': 'fa-solid fa-gear',
  'mdi-cog-outline': 'fa-solid fa-gear',
  'mdi-settings': 'fa-solid fa-gear',
  'mdi-settings-outline': 'fa-solid fa-gear',
  'mdi-sliders': 'fa-solid fa-sliders',
  'mdi-filter': 'fa-solid fa-filter',
  'mdi-filter-variant': 'fa-solid fa-filter',
  'mdi-sort': 'fa-solid fa-arrow-down-wide-short',
  'mdi-sort-variant': 'fa-solid fa-arrow-down-wide-short',
  'mdi-funnel': 'fa-solid fa-filter',
  'mdi-search': 'fa-solid fa-search',
  'mdi-search-web': 'fa-solid fa-search',
  'mdi-magnify': 'fa-solid fa-magnifying-glass',
  'mdi-magnify-minus': 'fa-solid fa-search-minus',
  'mdi-magnify-plus': 'fa-solid fa-search-plus',
  'mdi-fit-screen': 'fa-solid fa-expand',
  'mdi-focus': 'fa-solid fa-crosshair',
  'mdi-focus-outline': 'fa-solid fa-crosshair',
  'mdi-zoom-in': 'fa-solid fa-magnifying-glass-plus',
  'mdi-zoom-out': 'fa-solid fa-magnifying-glass-minus',
  'mdi-xml': 'fa-solid fa-code',
  'mdi-file-xml': 'fa-solid fa-code',
  'mdi-file-code': 'fa-solid fa-code',
  'mdi-code-tags': 'fa-solid fa-code',
  'mdi-code-braces': 'fa-solid fa-code',
  'mdi-code-2': 'fa-solid fa-code',
  'mdi-format': 'fa-solid fa-font',
  'mdi-format-bold': 'fa-solid fa-bold',
  'mdi-format-italic': 'fa-solid fa-italic',
  'mdi-format-underline': 'fa-solid fa-underline',
  'mdi-format-strikethrough': 'fa-solid fa-strikethrough',
  'mdi-format-list-bulleted': 'fa-solid fa-list',
  'mdi-format-list-numbered': 'fa-solid fa-list-ol',
  'mdi-format-quote': 'fa-solid fa-quote-right',
  'mdi-format-code': 'fa-solid fa-code',
  'mdi-align-left': 'fa-solid fa-align-left',
  'mdi-align-center': 'fa-solid fa-align-center',
  'mdi-align-right': 'fa-solid fa-align-right',
  'mdi-align-justify': 'fa-solid fa-align-justify',
  'mdi-border-all': 'fa-solid fa-table',
  'mdi-border-none': 'fa-solid fa-border-none',
  'mdi-border-left': 'fa-solid fa-border-left',
  'mdi-border-right': 'fa-solid fa-border-right',
  'mdi-border-top': 'fa-solid fa-border-top',
  'mdi-border-bottom': 'fa-solid fa-border-bottom',
  'mdi-horizontal-rule': 'fa-solid fa-minus',
  'mdi-link-variant': 'fa-solid fa-link',
  'mdi-image': 'fa-solid fa-image',
  'mdi-image-outline': 'fa-solid fa-image',
  'mdi-image-plus': 'fa-solid fa-image-plus',
  'mdi-image-off': 'fa-solid fa-image-xmark',
  'mdi-video': 'fa-solid fa-video',
  'mdi-video-outline': 'fa-solid fa-video',
  'mdi-youtube': 'fa-brands fa-youtube',
  'mdi-twitter': 'fa-brands fa-twitter',
  'mdi-facebook': 'fa-brands fa-facebook',
  'mdi-instagram': 'fa-brands fa-instagram',
  'mdi-discord': 'fa-brands fa-discord',
  'mdi-telegram': 'fa-brands fa-telegram',
  'mdi-qqchat': 'fa-brands fa-qq',
  'mdi-wechat': 'fa-brands fa-weixin',
  'mdi-whatsapp': 'fa-brands fa-whatsapp',
  'mdi-phone': 'fa-solid fa-phone',
  'mdi-website': 'fa-solid fa-globe',
  'mdi-refresh': 'fa-solid fa-rotate-right',
  'mdi-reload': 'fa-solid fa-rotate-right',
  'mdi-delete-forever': 'fa-solid fa-trash',
  'mdi-delete-sweep': 'fa-solid fa-trash',
  'mdi-restore': 'fa-solid fa-rotate-left',
  'mdi-cloud-download': 'fa-solid fa-cloud-download',
  'mdi-cloud-upload': 'fa-solid fa-cloud-upload',
  'mdi-cloud-outline': 'fa-solid fa-cloud',
  'mdi-cloud-off': 'fa-solid fa-cloud-xmark',
  'mdi-export': 'fa-solid fa-file-export',
  'mdi-import': 'fa-solid fa-file-import',
  'mdi-send-outline': 'fa-solid fa-paper-plane',
  'mdi-forward': 'fa-solid fa-forward',
  'mdi-email-open': 'fa-solid fa-envelope-open',
  'mdi-email-outline': 'fa-solid fa-envelope',
  'mdi-email-alert': 'fa-solid fa-envelope-circle-check',
  'mdi-email-check': 'fa-solid fa-envelope-check',
  'mdi-email-off': 'fa-solid fa-envelope-xmark',
  'mdi-spam': 'fa-solid fa-envelope-open-text',
  'mdi-trash-can': 'fa-solid fa-trash',
  'mdi-trash-can-outline': 'fa-solid fa-trash',
  'mdi-delete-empty': 'fa-solid fa-trash',
  'mdi-delete-outline': 'fa-solid fa-trash',
  'mdi-archive': 'fa-solid fa-archive',
  'mdi-archive-outline': 'fa-solid fa-archive',
  'mdi-star-box': 'fa-solid fa-star',
  'mdi-star-box-outline': 'fa-regular fa-star',
  'mdi-flag-outline': 'fa-regular fa-flag',
  'mdi-flag-cancel': 'fa-solid fa-flag',
  'mdi-label': 'fa-solid fa-tag',
  'mdi-label-outline': 'fa-solid fa-tag',
  'mdi-bookmark-minus': 'fa-solid fa-bookmark-minus',
  'mdi-bookmark-plus': 'fa-solid fa-bookmark-plus',
  'mdi-calendar-outline': 'fa-solid fa-calendar',
  'mdi-calendar-today': 'fa-solid fa-calendar-day',
  'mdi-calendar-month': 'fa-solid fa-calendar-days',
  'mdi-calendar-year': 'fa-solid fa-calendar',
  'mdi-calendar-clock': 'fa-solid fa-calendar-clock',
  'mdi-calendar-check': 'fa-solid fa-calendar-check',
  'mdi-calendar-plus': 'fa-solid fa-calendar-plus',
  'mdi-calendar-minus': 'fa-solid fa-calendar-minus',
  'mdi-calendar-edit': 'fa-solid fa-calendar-pen',
  'mdi-calendar-off': 'fa-solid fa-calendar-xmark',
  'mdi-clock-outline': 'fa-solid fa-clock',
  'mdi-clock-alert': 'fa-solid fa-clock-exclamation',
  'mdi-clock-check': 'fa-solid fa-clock-check',
  'mdi-clock-off': 'fa-solid fa-clock-xmark',
  'mdi-bell-plus': 'fa-solid fa-bell-plus',
  'mdi-bell-minus': 'fa-solid fa-bell-minus',
  'mdi-notification': 'fa-solid fa-bell',
  'mdi-notification-clear-all': 'fa-solid fa-bell',
  'mdi-rss-box': 'fa-solid fa-rss',
  'mdi-wifi-outline': 'fa-solid fa-wifi',
  'mdi-wifi-off': 'fa-solid fa-wifi-slash',
  'mdi-signal': 'fa-solid fa-signal',
  'mdi-signal-cellular': 'fa-solid fa-signal',
  'mdi-battery': 'fa-solid fa-battery-full',
  'mdi-battery-outline': 'fa-solid fa-battery-full',
  'mdi-battery-10': 'fa-solid fa-battery-empty',
  'mdi-battery-20': 'fa-solid fa-battery-quarter',
  'mdi-battery-30': 'fa-solid fa-battery-half',
  'mdi-battery-50': 'fa-solid fa-battery-three-quarters',
  'mdi-battery-60': 'fa-solid fa-battery-three-quarters',
  'mdi-battery-80': 'fa-solid fa-battery-full',
  'mdi-battery-90': 'fa-solid fa-battery-full',
  'mdi-battery-charging': 'fa-solid fa-battery-charging',
  'mdi-battery-warning': 'fa-solid fa-battery-low',
  'mdi-battery-alert': 'fa-solid fa-battery-low',
  'mdi-power': 'fa-solid fa-power-off',
  'mdi-power-plug': 'fa-solid fa-plug',
  'mdi-flash': 'fa-solid fa-bolt',
  'mdi-flash-off': 'fa-solid fa-bolt-slash',
  'mdi-ethernet': 'fa-solid fa-network-wired',
  'mdi-cable': 'fa-solid fa-network-wired',
  'mdi-router': 'fa-solid fa-network-wired',
  'mdi-switch': 'fa-solid fa-toggle-on',
  'mdi-toggle-switch': 'fa-solid fa-toggle-on',
  'mdi-toggle-switch-off': 'fa-solid fa-toggle-off',
  'mdi-toggle-on': 'fa-solid fa-toggle-on',
  'mdi-toggle-off': 'fa-solid fa-toggle-off',
  'mdi-gauge': 'fa-solid fa-gauge',
  'mdi-gauge-full': 'fa-solid fa-gauge',
  'mdi-gauge-empty': 'fa-solid fa-gauge',
  'mdi-gauge-low': 'fa-solid fa-gauge',
  'mdi-gauge-medium': 'fa-solid fa-gauge',
  'mdi-gauge-high': 'fa-solid fa-gauge',
  'mdi-speedometer': 'fa-solid fa-gauge',
  'mdi-tachometer': 'fa-solid fa-gauge',
  'mdi-fuel': 'fa-solid fa-gauge',
  'mdi-fuel-gauge': 'fa-solid fa-gauge',
  'mdi-temp': 'fa-solid fa-temperature-three-quarters',
  'mdi-thermometer': 'fa-solid fa-thermometer',
  'mdi-thermometer-low': 'fa-solid fa-temperature-arrow-down',
  'mdi-thermometer-medium': 'fa-solid fa-temperature-half',
  'mdi-thermometer-high': 'fa-solid fa-temperature-arrow-up',
  'mdi-water-percent': 'fa-solid fa-droplet',
  'mdi-humidity': 'fa-solid fa-droplet',
  'mdi-pressure': 'fa-solid fa-gauge',
  'mdi-air-filter': 'fa-solid fa-wind',
  'mdi-air-freshener': 'fa-solid fa-wind',
  'mdi-weather': 'fa-solid fa-cloud-sun',
  'mdi-weather-partly-cloudy': 'fa-solid fa-cloud-sun',
  'mdi-weather-cloudy': 'fa-solid fa-cloud',
  'mdi-weather-rainy': 'fa-solid fa-cloud-rain',
  'mdi-weather-lightning': 'fa-solid fa-cloud-bolt',
  'mdi-weather-snowy': 'fa-solid fa-snowflake',
  'mdi-weather-windy': 'fa-solid fa-wind',
  'mdi-sunny': 'fa-solid fa-sun',
  'mdi-night': 'fa-solid fa-moon',
  'mdi-rain': 'fa-solid fa-cloud-rain',
  'mdi-lightning': 'fa-solid fa-cloud-bolt',
  'mdi-fog': 'fa-solid fa-cloud',
  'mdi-hail': 'fa-solid fa-cloud-hail',
  'mdi-thunderstorm': 'fa-solid fa-cloud-bolt',
  'mdi-tornado': 'fa-solid fa-tornado',
  'mdi-hurricane': 'fa-solid fa-cloud-bolt',
  'mdi-drought': 'fa-solid fa-sun',
  'mdi-flood': 'fa-solid fa-water',
  'mdi-tsunami': 'fa-solid fa-waves',
  'mdi-earthquake': 'fa-solid fa-earthquake',
  'mdi-volcano': 'fa-solid fa-mountain',
  'mdi-forest': 'fa-solid fa-tree',
  'mdi-beach': 'fa-solid fa-umbrella-beach',
  'mdi-sunset': 'fa-solid fa-sun',
  'mdi-sunrise': 'fa-solid fa-sun',
  'mdi-moon-waxing': 'fa-solid fa-moon',
  'mdi-moon-waning': 'fa-solid fa-moon',
  'mdi-moon-new': 'fa-solid fa-circle',
  'mdi-moon-full': 'fa-solid fa-moon',
  'mdi-star': 'fa-solid fa-star',
  'mdi-star-half': 'fa-solid fa-star-half-stroke',
  'mdi-star-outline': 'fa-regular fa-star',
  'mdi-star-off': 'fa-regular fa-star',
  'mdi-star-check': 'fa-solid fa-star',
  'mdi-star-alert': 'fa-solid fa-star',
  'mdi-star-edit': 'fa-solid fa-star',
  'mdi-star-plus': 'fa-solid fa-star',
  'mdi-star-minus': 'fa-solid fa-star',
  'mdi-star-multiple': 'fa-solid fa-star',
  'mdi-star-group': 'fa-solid fa-star',
  'mdi-star-settings': 'fa-solid fa-star',
  'mdi-star-search': 'fa-solid fa-star',
  'mdi-star-off-outline': 'fa-regular fa-star',
  'mdi-star-check-outline': 'fa-regular fa-star',
  'mdi-star-alert-outline': 'fa-regular fa-star',
  'mdi-star-edit-outline': 'fa-regular fa-star',
  'mdi-star-plus-outline': 'fa-regular fa-star',
  'mdi-star-minus-outline': 'fa-regular fa-star',
  'mdi-star-multiple-outline': 'fa-regular fa-star',
  'mdi-star-group-outline': 'fa-regular fa-star',
  'mdi-star-settings-outline': 'fa-regular fa-star',
  'mdi-star-search-outline': 'fa-regular fa-star'
}

const getIconClass = (icon) => {
  if (!icon) return ''
  if (icon.startsWith('fa-')) return icon
  return mdiToFa[icon] || ''
}

const defaultTitle = {
  id: 0,
  name: '注册用户',
  color: '#625B71',
  icon: 'mdi-account',
  description: '系统默认头衔'
}

const displayTitles = computed(() => {
  const titles = props.user.titles || []
  const visibleTitles = titles.slice(0, props.maxVisibleTitles)
  if (visibleTitles.length === 0) {
    return [defaultTitle]
  }
  return visibleTitles
})

const nameSizeClass = computed(() => {
  if (props.size >= 64) return 'text-h6 font-weight-bold'
  if (props.size >= 48) return 'text-body-1 font-weight-bold'
  return 'text-body-2 font-weight-medium'
})

const adjustColorOpacity = (color, opacity) => {
  if (!color) return `rgba(103, 80, 164, ${opacity})`
  if (color.startsWith('#')) {
    const r = parseInt(color.slice(1, 3), 16)
    const g = parseInt(color.slice(3, 5), 16)
    const b = parseInt(color.slice(5, 7), 16)
    return `rgba(${r}, ${g}, ${b}, ${opacity})`
  }
  return color
}

defineExpose({
  displayTitles
})
</script>

<style scoped>
.user-avatar {
  display: flex;
  align-items: center;
  min-width: 0;
}

.avatar-wrapper {
  border-radius: 50%;
  overflow: hidden;
  flex-shrink: 0;
}

.avatar-img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.user-info {
  min-width: 0;
  flex-shrink: 1;
  margin-left: 12px;
}

.user-name {
  line-height: 1.3;
  word-break: break-word;
}

.titles-row {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  margin-top: 4px;
}

.title-chip {
  display: inline-flex;
  align-items: center;
  gap: 2px;
  padding: 2px 8px;
  border-radius: 12px;
  font-size: 12px;
  font-weight: 500;
  height: 20px;
}

.chip-icon {
  font-size: 10px;
}

.text-h6 {
  font-size: 18px;
}

.text-body-1 {
  font-size: 16px;
}

.text-body-2 {
  font-size: 14px;
}

.font-weight-bold {
  font-weight: 600;
}

.font-weight-medium {
  font-weight: 500;
}

.d-flex {
  display: flex;
}

.align-center {
  align-items: center;
}
</style>