// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/register": {
            "post": {
                "description": "注册新用户",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["认证"],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["username", "qq_number", "display_name", "password"],
                            "properties": {
                                "username": {"type": "string"},
                                "qq_number": {"type": "string"},
                                "display_name": {"type": "string"},
                                "password": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "注册成功"},
                    "400": {"description": "参数错误"},
                    "500": {"description": "服务器错误"}
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "用户登录",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["认证"],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["username", "password"],
                            "properties": {
                                "username": {"type": "string"},
                                "password": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "登录成功"},
                    "401": {"description": "认证失败"},
                    "500": {"description": "服务器错误"}
                }
            }
        },
        "/api/articles": {
            "get": {
                "description": "获取文章列表",
                "produces": ["application/json"],
                "tags": ["文章"],
                "summary": "获取文章列表",
                "parameters": [
                    {"name": "page", "in": "query", "type": "integer"},
                    {"name": "page_size", "in": "query", "type": "integer"},
                    {"name": "category_id", "in": "query", "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "成功"}
                }
            },
            "post": {
                "description": "创建新文章",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["文章"],
                "summary": "创建文章",
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "description": "文章信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["title", "content", "category_id"],
                            "properties": {
                                "title": {"type": "string"},
                                "content": {"type": "string"},
                                "category_id": {"type": "integer"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "创建成功"},
                    "401": {"description": "未授权"},
                    "500": {"description": "服务器错误"}
                }
            }
        },
        "/api/articles/{id}": {
            "get": {
                "description": "获取文章详情",
                "produces": ["application/json"],
                "tags": ["文章"],
                "summary": "获取文章详情",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "成功"},
                    "404": {"description": "文章不存在"}
                }
            },
            "put": {
                "description": "更新文章",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["文章"],
                "summary": "更新文章",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"},
                    {
                        "description": "文章信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "title": {"type": "string"},
                                "content": {"type": "string"},
                                "category_id": {"type": "integer"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "更新成功"},
                    "401": {"description": "未授权"},
                    "403": {"description": "无权限"},
                    "404": {"description": "文章不存在"}
                }
            },
            "delete": {
                "description": "删除文章",
                "tags": ["文章"],
                "summary": "删除文章",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "删除成功"},
                    "401": {"description": "未授权"},
                    "403": {"description": "无权限"},
                    "404": {"description": "文章不存在"}
                }
            }
        },
        "/api/articles/{id}/like": {
            "post": {
                "description": "点赞文章",
                "tags": ["文章"],
                "summary": "点赞文章",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "点赞成功"},
                    "401": {"description": "未授权"}
                }
            },
            "delete": {
                "description": "取消点赞",
                "tags": ["文章"],
                "summary": "取消点赞",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "取消成功"},
                    "401": {"description": "未授权"}
                }
            }
        },
        "/api/articles/{id}/comments": {
            "get": {
                "description": "获取文章评论",
                "produces": ["application/json"],
                "tags": ["评论"],
                "summary": "获取评论",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "成功"}
                }
            },
            "post": {
                "description": "添加评论",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["评论"],
                "summary": "添加评论",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"},
                    {
                        "description": "评论内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["content"],
                            "properties": {
                                "content": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "评论成功"},
                    "401": {"description": "未授权"}
                }
            }
        },
        "/api/comments/{id}": {
            "delete": {
                "description": "删除评论",
                "tags": ["评论"],
                "summary": "删除评论",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "删除成功"},
                    "401": {"description": "未授权"},
                    "403": {"description": "无权限"}
                }
            }
        },
        "/api/categories": {
            "get": {
                "description": "获取所有分区",
                "produces": ["application/json"],
                "tags": ["分区"],
                "summary": "获取分区列表",
                "responses": {
                    "200": {"description": "成功"}
                }
            },
            "post": {
                "description": "创建分区",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["分区"],
                "summary": "创建分区",
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "description": "分区信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["name"],
                            "properties": {
                                "name": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "创建成功"},
                    "401": {"description": "未授权"},
                    "403": {"description": "需要管理员权限"}
                }
            }
        },
        "/api/categories/{id}": {
            "put": {
                "description": "更新分区",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["分区"],
                "summary": "更新分区",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"},
                    {
                        "description": "分区信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "更新成功"},
                    "401": {"description": "未授权"},
                    "403": {"description": "需要管理员权限"}
                }
            },
            "delete": {
                "description": "删除分区",
                "tags": ["分区"],
                "summary": "删除分区",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "删除成功"},
                    "401": {"description": "未授权"},
                    "403": {"description": "需要管理员权限"}
                }
            }
        },
        "/api/profile": {
            "get": {
                "description": "获取当前用户信息",
                "produces": ["application/json"],
                "tags": ["用户"],
                "summary": "获取用户信息",
                "security": [{"Bearer": []}],
                "responses": {
                    "200": {"description": "成功"},
                    "401": {"description": "未授权"}
                }
            },
            "put": {
                "description": "更新用户信息",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["用户"],
                "summary": "更新用户信息",
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "display_name": {"type": "string"},
                                "bio": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "更新成功"},
                    "401": {"description": "未授权"}
                }
            }
        },
        "/api/upload/avatar": {
            "post": {
                "description": "上传头像",
                "consumes": ["multipart/form-data"],
                "produces": ["application/json"],
                "tags": ["上传"],
                "summary": "上传头像",
                "security": [{"Bearer": []}],
                "responses": {
                    "200": {"description": "上传成功"},
                    "401": {"description": "未授权"}
                }
            }
        },
        "/api/upload/image": {
            "post": {
                "description": "上传图片",
                "consumes": ["multipart/form-data"],
                "produces": ["application/json"],
                "tags": ["上传"],
                "summary": "上传图片",
                "security": [{"Bearer": []}],
                "responses": {
                    "200": {"description": "上传成功"},
                    "401": {"description": "未授权"}
                }
            }
        },
        "/api/sidebar-config": {
            "get": {
                "description": "获取侧边栏配置",
                "produces": ["application/json"],
                "tags": ["配置"],
                "summary": "获取侧边栏配置",
                "responses": {
                    "200": {"description": "成功"}
                }
            },
            "put": {
                "description": "更新侧边栏配置",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["配置"],
                "summary": "更新侧边栏配置",
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "description": "侧边栏配置",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "items": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "title": {"type": "string"},
                                            "link": {"type": "string"},
                                            "icon": {"type": "string"}
                                        }
                                    }
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "更新成功"},
                    "401": {"description": "未授权"},
                    "403": {"description": "需要管理员权限"}
                }
            }
        },
        "/api/announcement": {
            "get": {
                "description": "获取公告",
                "produces": ["application/json"],
                "tags": ["配置"],
                "summary": "获取公告",
                "responses": {
                    "200": {"description": "成功"}
                }
            },
            "put": {
                "description": "更新公告",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["配置"],
                "summary": "更新公告",
                "security": [{"Bearer": []}],
                "parameters": [
                    {
                        "description": "公告内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "content": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "更新成功"},
                    "401": {"description": "未授权"},
                    "403": {"description": "需要管理员权限"}
                }
            }
        },
        "/api/deletion-requests": {
            "get": {
                "description": "获取删除请求列表",
                "produces": ["application/json"],
                "tags": ["管理"],
                "summary": "获取删除请求",
                "security": [{"Bearer": []}],
                "responses": {
                    "200": {"description": "成功"},
                    "401": {"description": "未授权"},
                    "403": {"description": "需要管理员权限"}
                }
            }
        },
        "/api/deletion-requests/{id}/approve": {
            "post": {
                "description": "批准删除请求",
                "tags": ["管理"],
                "summary": "批准删除",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "批准成功"},
                    "401": {"description": "未授权"},
                    "403": {"description": "需要管理员权限"}
                }
            }
        },
        "/api/deletion-requests/{id}/reject": {
            "post": {
                "description": "拒绝删除请求",
                "tags": ["管理"],
                "summary": "拒绝删除",
                "security": [{"Bearer": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"}
                ],
                "responses": {
                    "200": {"description": "拒绝成功"},
                    "401": {"description": "未授权"},
                    "403": {"description": "需要管理员权限"}
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.3.3",
	Host:             "0.0.0.0:3620",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "校园论坛 API 文档",
	Description:      "校园论坛后端 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
